ssh:
  identityFile: ~/.ssh/pwcli
  user: mshaxted
  jumpHost: workspace
  proxyCommand: "pw ssh --proxy-command %h"

sites:
  - host: genai.mil
    port: 443
    localPort: 10443
  - host: gemini.genai.mil
    port: 443
    localPort: 10444
  - host: vertexaisearch.cloud.google
    port: 443
    localPort: 10445
  - host: content-us-discoveryengine.googleapis.com
    port: 443
    localPort: 10446
